# 在这里写上你的代码 :-)
# int(整数)，float(浮点数)，bool(逻辑型,布尔型)，complex(复数)，str(字符串)，list(列表)，dict(字典)，set(集)，tuple(元组)
a=isinstance(32768,int)
print(a)
a=isinstance(1,bool)
print(a)
a=isinstance(True,bool)
print(a)
a=isinstance('32768',str)
print(a)
a=isinstance([3,2,7,6,8],list)
print(a)
a=isinstance((32,7,68),tuple)
print(a)

