# 在这里写上你的代码 :-)
mylist = iter(["apple", "banana", "cherry"])
x = next(mylist)
print(x)
x = next(mylist)
print(x)
x = next(mylist)
print(x)

mylist = iter({"apple2", "banana2", "cherry2"})
x = next(mylist)
print(x)
x = next(mylist)
print(x)
x = next(mylist)
print(x)
